### PR TITLE
Issue #3111628 by chr.fritsch: Hardcoded result size limit in the select2 autocomplete widget

### PR DESCRIPTION
**Pull request by chrfritsch**
Here is the corresponding core issue https://www.drupal.org/project/drupal/issues/2863188

### CODE REVIEW

**Comment by chrfritsch** [comment]
All the code is copied from https://git.drupalcode.org/project/drupal/commit/438f38397b32e2badfcd9f2cc2059e2758a64faa

**Review by ol0lll — CHANGES_REQUESTED** [review]
Looks good.
It would be nice to test this by setting match_limit and count the result.

**Comment by chrfritsch** [comment]
I added a test

**Review by ol0lll — APPROVED** [review]
Very nice, lets hit it.

**Pull request merged**
